[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
(
  /(\.git|\.venv|venv|env|build|dist|\.mypy_cache|\.pytest_cache|\.ruff_cache|artifact|artifact_ci)/
)
'''

[tool.ruff]
# מקובל להתעלם מאורך שורה ב-Ruff ולתת ל-Black לאכוף עימוד.
line-length = 88
target-version = "py311"
src = ["src", "lucy_agent", "."]  # תקן נתיבים לפרויקט שלך
exclude = [
  ".git",
  ".venv",
  "venv",
  "env",
  "build",
  "dist",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
  "artifact",
  "artifact_ci",
]

[tool.ruff.lint]
# סט חוקים בסיסי ונקי; מתעלמים מ-E501 כדי לא להכפיל אכיפה מול Black
select = ["E", "F", "I", "B"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["lucy_agent", "src"]
combine-as-imports = true
force-sort-within-sections = true
