
[tool.black]
line-length = 100

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "B", "I", "UP"]
ignore = ["E501"]  # בשלב זה לא נכשלים על אורך שורה

[tool.ruff.lint.isort]
known-first-party = ["lucy_agent", "src"]
combine-as-imports = true
force-single-line = false
