[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
(
  /(\.git|\.venv|venv|env|build|dist|\.mypy_cache|\.pytest_cache|\.ruff_cache|artifact|artifact_ci)/
)
'''

[tool.ruff]
line-length = 88
target-version = "py311"
# סט חוקים בסיסי: שגיאות/אזהרות, ייבוא, באגים שכיחים
select = ["E", "F", "I", "B"]
ignore = []  # נוכל להוסיף בהמשך אם נדרש
src = ["."]
exclude = [
  ".git",
  ".venv",
  "venv",
  "env",
  "build",
  "dist",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
  "artifact",
  "artifact_ci",
]

[tool.ruff.lint.isort]
# יישור לרוחב שורה של 88 ופרופיל Black
known-first-party = ["."]
combine-as-imports = true
force-sort-within-sections = true

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "B", "I", "UP"]
ignore = ["E501"]
