name: CI - Agent
on:
  push:
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.github/workflows/agent.yml'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest mypy ruff || true
      - name: Lint (ruff)
        run: ruff check . || true
      - name: Typecheck (mypy)
        run: mypy . || true
      - name: Tests (pytest)
        run: pytest -q || true
