name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  agent-ci:
    name: Agent CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install pre-commit ruff black pytest httpx || true

      - name: Pre-commit (informational)
        run: pre-commit run -a || true

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (check)
        run: black --check .

      - name: Health smoke (local)
        env:
          AGENT_API_KEY: test-key
        run: |
          nohup python -m uvicorn src.main:app \
            --host 127.0.0.1 --port 8000 --workers 1 --no-access-log \
            > .api.log 2>&1 & echo $! > .uvicorn.pid
          sleep 2
          code=$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8000/health || echo 000)
          [[ "$code" == "200" ]] || (echo "health expected 200, got $code" && exit 1)
          kill "$(cat .uvicorn.pid)" 2>/dev/null || true
