name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Prepare artifact dirs (always)
        run: |
          set -euxo pipefail
          mkdir -p logs

      - name: Capture env
        run: |
          set -euxo pipefail
          {
            echo "=== uname -a ==="; uname -a
            echo "=== python -V ==="; python -V
            echo "=== pip --version ==="; pip --version
          } | tee logs/env.txt

      - name: Install deps (capture logs)
        run: |
          set -euxo pipefail
          python -m pip install -U pip setuptools wheel > >(tee logs/pip-bootstrap.out) 2> >(tee logs/pip-bootstrap.err >&2)
          python -m pip install -r requirements.txt -vvv > >(tee logs/pip-install.out) 2> >(tee logs/pip-install.err >&2)
          python -m pip check | tee logs/pip-check.out
          python -m pip freeze | tee logs/pip-freeze.txt

      - name: Import sanity (src-layout)
        run: |
          set -euxo pipefail
          export PYTHONPATH=src
          python - <<'PY'
import importlib
mods = ["fastapi","starlette","httpx"]
for m in mods:
    importlib.import_module(m)
importlib.import_module("lucy_agent.api")
print("import sanity OK")
PY

      - name: Run tests (pytest)
        run: |
          set -euxo pipefail
          export PYTHONPATH=src
          pytest -q -vv tests | tee logs/pytest.out
          test ${PIPESTATUS[0]} -eq 0

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: logs/**
          if-no-files-found: warn
          retention-days: 7
